# Generated by Django 5.2.17 on 2026-10-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="source id",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="start time"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="end time"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="location"
                    ),
                ),
                (
                    "park_names",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="park names"
                    ),
                ),
                (
                    "park_ids",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="park ids"
                    ),
                ),
                (
                    "categories",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="categories"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="longitude"),
                ),
                (
                    "event_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="event URL"
                    ),
                ),
                (
                    "registration_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="registration URL"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="image URL"
                    ),
                ),
                (
                    "instructor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="instructor"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="contact phone"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("upcoming", "Upcoming"), ("done", "Done")],
                        db_index=True,
                        default="upcoming",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(max_length=64, verbose_name="content hash"),
                ),
                (
                    "source_version",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="source version"
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="first seen at"
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last synced at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "ordering": ["start_time", "end_time", "title"],
            },
        ),
    ]
