# Generated by Django 5.2.17 on 2026-10-09 22:07

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.CombinedSearchVector(
                        django.contrib.postgres.search.SearchVector(
                            "title", config="english", weight="A"
                        ),
                        "||",
                        django.contrib.postgres.search.SearchVector(
                            "categories",
                            "park_names",
                            "location",
                            config="english",
                            weight="B",
                        ),
                        django.contrib.postgres.search.SearchConfig("english"),
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "description", config="english", weight="C"
                    ),
                    django.contrib.postgres.search.SearchConfig("english"),
                ),
                name="event_search_gin",
            ),
        ),
    ]
