# Generated by Django 5.2.17 on 2026-09-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(
                blank=True,
                help_text="Optional. Tell us about yourself in 300 characters or fewer.",
                max_length=300,
                verbose_name="bio",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True, upload_to="profile_photos/", verbose_name="profile photo"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pronouns",
            field=models.CharField(
                blank=True,
                help_text="Optional. For example, she/her, he/him, or they/them.",
                max_length=50,
                verbose_name="pronouns",
            ),
        ),
    ]
